version: '3'

services:

  batching-request:
    image: nginx:1.19.7-alpine
    expose:
      - 80
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./script:/etc/nginx/script
